# Generated by Django 2.0.7 on 2018-07-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
