# Generated by Django 2.0.7 on 2018-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0006_auto_20180711_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
