# Generated by Django 2.0.7 on 2018-07-14 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atest', '0008_auto_20180714_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null='false', on_delete='null', related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
