# Generated by Django 2.0.7 on 2018-07-16 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atest', '0009_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.ForeignKey(null='false', on_delete='null', related_name='PassingTests', to='atest.Test')),
                ('userID', models.ForeignKey(null='false', on_delete='null', related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('answersID', models.ForeignKey(null='false', on_delete='null', related_name='SessionAnswers', to='atest.Answer')),
                ('questionID', models.ForeignKey(null='false', on_delete='null', related_name='SessionQuestions', to='atest.Question')),
                ('sessionID', models.ForeignKey(null='false', on_delete='null', related_name='Sessions', to='atest.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(null='false', on_delete='null', related_name='CurrentAnswers', to='atest.Answer'),
        ),
        migrations.AlterField(
            model_name='result',
            name='userId',
            field=models.ForeignKey(null='false', on_delete='null', related_name='UsersToResult', to='atest.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null='false', on_delete='null', related_name='UsersProfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
