# Generated by Django 2.0.7 on 2018-07-16 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0010_auto_20180716_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswers',
            name='data',
        ),
        migrations.AddField(
            model_name='usersanswers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 22, 30, 57, 936119)),
        ),
    ]
