# Generated by Django 2.0.7 on 2018-07-16 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0011_auto_20180716_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 22, 40, 10, 328294)),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
