# Generated by Django 2.0.7 on 2018-07-16 19:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atest', '0012_auto_20180716_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.ForeignKey(null='false', on_delete='null', related_name='PassingTests', to='atest.Test')),
                ('userID', models.ForeignKey(null='false', on_delete='null', related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='testID',
        ),
        migrations.RemoveField(
            model_name='session',
            name='userID',
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(default='zaebalo'),
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 22, 54, 53, 392675)),
        ),
    ]
