# Generated by Django 2.0.7 on 2018-07-16 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atest', '0013_auto_20180716_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 22, 55, 29, 510952)),
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='sessionID',
            field=models.ForeignKey(null='false', on_delete='null', related_name='Sessions', to='atest.TestSession'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
